#!/bin/bash
sudo bash -c "echo 0 > /proc/sys/kernel/yama/ptrace_scope"
cd ~/mcsim
cd McSim 
#make INCS=-I/home/lorabit/mcsim/pin/extras/xed2017/include/xed -j 8 >> compiles.log
make INCS=-I/home/lorabit/mcsim/pin/extras/xed2/include -j 8 >> compiles.log
cd ../Pthread
make TOOLS_DIR=/home/lorabit/mcsim/pin/source/tools -j 8 >>compiles.log
cd ..
McSim/mcsim -mdfile ./Apps/md/md-o3-closed.py -runfile ./Apps/list/run-test.py
